export type PricingCategory = "web" | "marketing" | "software";

export interface PricingPackage {
  id: string;
  name: string;
  priceInr: number;
  priceUsd?: number;
  priceLabel?: string;
  category: PricingCategory;
  popular?: boolean;
  features: string[];
}

export const PRICING_PACKAGES: PricingPackage[] = [
  {
    id: "basic-web-presence",
    name: "Basic Web Presence Package",
    priceInr: 3499,
    priceUsd: 79,
    category: "web",
    features: [
      "Paid Domain",
      "Free Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "Single Page Website",
      "Contact Form Integration",
      "Basic SEO Optimization",
      "Client Testimonials Section",
      "Mobile-Friendly Layout",
      "Social Media Integration",
    ],
  },
  {
    id: "startup-essentials",
    name: "Startup Essentials Package",
    priceInr: 6999,
    priceUsd: 179,
    category: "web",
    popular: true,
    features: [
      "Free Domain (1 Year)",
      "Free Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "8 Pages",
      "Contact Form Integration",
      "Basic SEO Optimization",
      "Client Testimonials Section",
      "Mobile-Friendly Layout",
      "Social Media Integration",
      "Blog/News Section",
      "Image/Video Gallery",
    ],
  },
  {
    id: "ecommerce-starter",
    name: "E-Commerce Starter Package",
    priceInr: 9999,
    priceUsd: 249,
    category: "web",
    features: [
      "Free Domain (1 Year)",
      "Free Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "10 Pages",
      "E-Commerce Functionality (Up to 20 Products)",
      "Shopping Cart Integration",
      "Client Testimonials Section",
      "Payment Gateway Integration",
      "Contact Form Integration",
      "Basic SEO Optimization",
      "Mobile-Friendly Layout",
      "Admin Panel Access",
    ],
  },
  {
    id: "bloggers-delight",
    name: "Bloggers' Delight Package",
    priceInr: 8999,
    priceUsd: 199,
    category: "web",
    features: [
      "Free Domain (1 Year)",
      "Free Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "10 Pages",
      "Blog Section",
      "Blog Category",
      "Contact Form Integration",
      "Basic SEO Optimization",
      "Client Testimonials Section",
      "Mobile-Friendly Layout",
      "Social Media Integration",
      "Image/Video Gallery",
    ],
  },
  {
    id: "advanced-portfolio",
    name: "Advanced Portfolio Package",
    priceInr: 12999,
    priceUsd: 299,
    category: "web",
    features: [
      "Free Domain (1 Year)",
      "Free Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "12 Pages",
      "Custom Portfolio Section",
      "Contact Form Integration",
      "Client Testimonials Section",
      "Basic SEO Optimization",
      "Mobile-Friendly Layout",
      "Social Media Integration",
      "Blog/News Section",
      "Image/Video Gallery",
      "Letterhead Design",
      "Visiting Card Design",
    ],
  },
  {
    id: "professional-business",
    name: "Professional Business Package",
    priceInr: 14999,
    priceUsd: 349,
    category: "web",
    popular: true,
    features: [
      "Free Domain (1 Year)",
      "Free Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "Up to 15 Pages",
      "Customized Graphics and Icons",
      "Contact Form Integration",
      "Client Testimonials Section",
      "Advanced SEO Optimization",
      "Mobile-Friendly Layout",
      "Social Media Integration",
      "Blog/News Section",
      "Image/Video Gallery",
    ],
  },
  {
    id: "corporate-excellence",
    name: "Corporate Excellence Package",
    priceInr: 29999,
    priceUsd: 549,
    category: "web",
    features: [
      "Free Domain (3 Years)",
      "Free Hosting (3 Years)",
      "Free SSL Certificate (3 Years)",
      "Responsive Design",
      "Up to 30 Pages",
      "Free 2D Logo",
      "Letterhead Design",
      "Client Testimonials Section",
      "Visiting Card Design",
      "Contact Form Integration",
      "Customized Graphics and Icons",
      "Advanced SEO Optimization",
      "Mobile-Friendly Layout",
      "Social Media Integration",
      "Blog/News Section",
      "Image/Video Gallery",
      "Advanced Security Features",
    ],
  },
  {
    id: "multi-vendor-store",
    name: "Multi Vendor Online Store",
    priceInr: 34999,
    priceUsd: 1199,
    category: "web",
    features: [
      "Free Domain (1 Year)",
      "Personal Shared Hosting (1 Year)",
      "Free SSL Certificate (1 Year)",
      "Responsive Design",
      "Unlimited Pages",
      "Customized E-Commerce Functionality",
      "Vendor Registration",
      "UPI Payment Gateway Integration",
      "Product Listings",
      "Contact Form Integration",
      "Shopping Cart System",
      "Mobile-Friendly Layout",
      "Social Media Integration",
      "Review and Rating System",
      "Vendor Analytics Dashboard",
      "Customer Support",
      "Advanced Payment Options",
      "API Integrations",
    ],
  },
  {
    id: "social-media-marketing-monthly",
    name: "Social Media Marketing Package",
    priceInr: 14999,
    priceLabel: "/month",
    category: "marketing",
    features: [
      "15 Creative Posts & 5 Reels Posts",
      "Facebook & Instagram Management",
      "Story Designs",
      "Reels Posting Support",
      "Audience Engagement",
      "Hashtag Strategy",
      "Monthly Performance Report",
    ],
  },
  {
    id: "hrms-software",
    name: "HRMS Software Package",
    priceInr: 75000,
    category: "software",
    popular: true,
    features: [
      "Employee Management",
      "Attendance & Leave Management",
      "Payroll System",
      "Biometric Integration",
      "Recruitment Module",
      "Multi-Branch Support",
      "Admin Dashboard",
    ],
  },
];

export function getPackageById(id: string): PricingPackage | undefined {
  return PRICING_PACKAGES.find((p) => p.id === id);
}

export function formatInr(amount: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}
